# Generated code do not commit.
file(TO_CMAKE_PATH "/home/local/o22403372/flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "/home/iut45/Etudiants/o22403372/Documents/BUT2/cours-BUT2/MOBILE/TD/td2" PROJECT_DIR)

set(FLUTTER_VERSION "1.0.0+1" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 0 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 0 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 1 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=/home/local/o22403372/flutter"
  "PROJECT_DIR=/home/iut45/Etudiants/o22403372/Documents/BUT2/cours-BUT2/MOBILE/TD/td2"
  "DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9WRVJTSU9OPTMuMzguNw==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049M2I2MmVmYzJhMw==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NzhmYzMwMTJlNA==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMC43"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=/home/iut45/Etudiants/o22403372/Documents/BUT2/cours-BUT2/MOBILE/TD/td2/.dart_tool/package_config.json"
  "FLUTTER_TARGET=/home/iut45/Etudiants/o22403372/Documents/BUT2/cours-BUT2/MOBILE/TD/td2/lib/main.dart"
)
